# used for local development only
dev-env:
  image: postgres:11.5
  ports:
    - "5432:5432"
  environment:
    - "POSTGRES_PASSWORD=postgres"
    - "POSTGRES_USER=postgres"
    - "POSTGRES_DB=go_in_5_minutes_site_development"
