name: Go
on: [push]
jobs:

  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Run unit tests
      run: go test ./pkg/... ./views/...
  
  buffalo-build:
    name: Build with Buffalo
    runs-on: ubuntu-18.04
    container: gobuffalo/buffalo:v0.14.0
    steps:
      - run: buffalo build